version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      #time: "08:00"
      #timezone: Europe/Rome
    open-pull-requests-limit: 20
    versioning-strategy: increase
